package request

import "time"

type StaffInfo struct {
	ID                          int    `json:"id"`
	Name                        string `json:"name"`
	ResourceId                  int    `json:"resource_id"`
	CompanyId                   int    `json:"companyId"`
	ResourceCalendarId          int    `json:"resourceCalendarId"`
	MessageMainAttachmentId     int    `json:"messageMainAttachmentId"`
	Color                       string `json:"color"`
	DepartmentId                int    `json:"departmentId"`
	JobId                       int    `json:"jobId"`
	AddressId                   int    `json:"addressId"`
	WorkContactId               int    `json:"workContactId"`
	WorkLocationId              int    `json:"workLocationId"`
	UserId                      int    `json:"userId"`
	ParentId                    int    `json:"parentId"`
	CoachId                     int    `json:"coachId"`
	AddressHomeId               string `json:"addressHomeId"`
	CountryId                   int    `json:"countryId"`
	Children                    int    `json:"children"`
	CountryOfBirth              int    `json:"countryOfBirth"`
	BankAccountId               int    `json:"bankAccountId"`
	KmHomeWork                  int    `json:"kmHomeWork"`
	DepartureReasonId           int    `json:"departureReasonId"`
	CreateUid                   int    `json:"createUid"`
	WriteUid                    int    `json:"writeUid"`
	JobTitle                    string `json:"jobTitle"`
	WorkPhone                   string `json:"workPhone"`
	MobilePhone                 string `json:"mobilePhone"`
	WorkEmail                   string `json:"workEmail"`
	EmployeeType                string `json:"employeeType"`
	Gender                      string `json:"gender"`
	Marital                     string `json:"marital"`
	SpouseCompleteName          string `json:"spouseCompleteName"`
	PlaceOfBirth                string `json:"placeOfBirth"` // 出生地
	Ssnid                       string `json:"ssnid"`
	Sinid                       string `json:"sinid"`
	IdentificationId            string `json:"identificationId"`
	PassportId                  string `json:"passportId"`
	PermitNo                    string `json:"permitNo"`
	VisaNo                      string `json:"visaNo"`
	Certificate                 string `json:"certificate"`
	StudyField                  string `json:"studyField"`
	StudySchool                 string `json:"studySchool"` // 毕业学校
	EmergencyContact            string `json:"emergencyContact"`
	EmergencyPhone              string `json:"emergencyPhone"`
	Barcode                     string `json:"barcode"`
	Pin                         string `json:"pin"`
	SpouseBirthdate             string `json:"spouseBirthdate"`
	Birthday                    string `json:"birthday"` // 出生日期
	VisaExpire                  string `json:"visaExpire"`
	WorkPermitExpirationDate    string `json:"workPermitExpirationDate"`
	DepartureDate               string `json:"departureDate"`
	AdditionalNote              string `json:"additionalNote"`
	Notes                       string `json:"notes"`
	DepartureDescription        string `json:"departureDescription"`
	Active                      bool   `json:"active"`
	WorkPermitScheduledActivity bool   `json:"workPermitScheduledActivity"`
	CreateDate                  string `json:"createDate"`
	WriteDate                   string `json:"writeDate"`
	LastAttendanceId            string `json:"lastAttendanceId"`
	LastCheckIn                 string `json:"lastCheckIn"`
	LastCheckOut                string `json:"lastCheckOut"`
	ContractId                  string `json:"contractId"`
	Vehicle                     string `json:"vehicle"`
	FirstContractDate           string `json:"firstContractDate"`
	ContractWarning             bool   `json:"contractWarning"`
	LeaveManagerId              string `json:"leaveManagerId"`
	HourlyCost                  string `json:"hourlyCost"`
	PersonalMobile              string `json:"personalMobile"`
	JoiningDate                 string `json:"joiningDate"`
	IdExpiryDate                string `json:"idExpiryDate"`
	PassportExpiryDate          string `json:"passportExpiryDate"`
	ResignDate                  string `json:"resignDate"`
	Resigned                    bool   `json:"resigned"`
	Fired                       bool   `json:"fired"`
	ExpenseManagerId            int    `json:"expenseManagerId"`
	ResourceCalendarIds         int    `json:"resourceCalendarIds"`
	Nation                      int    `json:"nation"`
	Schoolgrade                 int    `json:"schoolgrade"`
	Appellation                 int    `json:"appellation"`
	BookingNumAm                int    `json:"bookingNumAm"`
	BookingNumPm                int    `json:"bookingNumPm"`
	BookingNumNg                int    `json:"bookingNumNg"`
	PoliticsStatus              string `json:"politicsStatus"`
	Tocompile                   string `json:"tocompile"`
	AppellationCode             string `json:"appellationCode"`
	Rank                        string `json:"rank"`
	AppellationTime             string `json:"appellationTime"`
	Note                        string `json:"note"`
	Introduction                string `json:"introduction"`
	GradeId                     int    `json:"gradeId"`
	RankId                      int    `json:"rankId"`
	NaturePosition              string `json:"naturePosition"`
	SurgeryCert                 string `json:"surgeryCert"`
	Inductiondate               string `json:"inductiondate"`
	Performanceclass            string `json:"performanceclass"`
	EduAppellation              string `json:"eduAppellation"`
	EduCategory                 string `json:"eduCategory"`
	PhysicianCert               string `json:"physicianCert"`
	PharmacistCert              string `json:"pharmacistCert"`
	NurseCert                   string `json:"nurseCert"`
	OperateCert                 string `json:"operateCert"`
	PrescriptionCert            string `json:"prescriptionCert"`
	SpecialistId                string `json:"specialistId"`
	NurseSpe                    string `json:"nurseSpe"`
	SpecialistDate              string `json:"specialistDate"`
	IsSpecialist                string `json:"isSpecialist"`
	EduSchool                   string `json:"eduSchool"`
	SurgeryGrade                string `json:"surgeryGrade"`
	PracticeCateg               string `json:"practiceCateg"`
	PhysicianAidCert            string `json:"physicianAidCert"`
	NativePlaceP                string `json:"nativePlaceP"`
	NativePlaceC                string `json:"nativePlaceC"`
	GraduationDate              string `json:"graduationDate"`
}

type BasicStaffInfo struct {
	ID                          int       `json:"id"`
	Name                        string    `json:"name"`
	ResourceId                  int       `json:"resource_id"`
	CompanyId                   int       `json:"companyId"`
	ResourceCalendarId          int       `json:"resourceCalendarId"`
	MessageMainAttachmentId     int       `json:"messageMainAttachmentId"`
	Color                       string    `json:"color"`
	DepartmentId                int       `json:"departmentId"`
	JobId                       int       `json:"jobId"`
	AddressId                   int       `json:"addressId"`
	WorkContactId               int       `json:"workContactId"`
	WorkLocationId              int       `json:"workLocationId"`
	UserId                      int       `json:"userId"`
	ParentId                    int       `json:"parentId"`
	CoachId                     int       `json:"coachId"`
	AddressHomeId               string    `json:"addressHomeId"`
	CountryId                   int       `json:"countryId"`
	Children                    int       `json:"children"`
	CountryOfBirth              int       `json:"countryOfBirth"`
	BankAccountId               int       `json:"bankAccountId"`
	KmHomeWork                  int       `json:"kmHomeWork"`
	DepartureReasonId           int       `json:"departureReasonId"`
	CreateUid                   int       `json:"createUid"`
	WriteUid                    int       `json:"writeUid"`
	JobTitle                    string    `json:"jobTitle"`
	WorkPhone                   string    `json:"workPhone"`
	MobilePhone                 string    `json:"mobilePhone"`
	WorkEmail                   string    `json:"workEmail"`
	EmployeeType                string    `json:"employeeType"`
	Gender                      string    `json:"gender"`
	Marital                     string    `json:"marital"`
	SpouseCompleteName          string    `json:"spouseCompleteName"`
	PlaceOfBirth                string    `json:"placeOfBirth"` // 出生地
	Ssnid                       string    `json:"ssnid"`
	Sinid                       string    `json:"sinid"`
	IdentificationId            string    `json:"identificationId"`
	PassportId                  string    `json:"passportId"`
	PermitNo                    string    `json:"permitNo"`
	VisaNo                      string    `json:"visaNo"`
	Certificate                 string    `json:"certificate"`
	StudyField                  string    `json:"studyField"`
	StudySchool                 string    `json:"studySchool"` // 毕业学校
	EmergencyContact            string    `json:"emergencyContact"`
	EmergencyPhone              string    `json:"emergencyPhone"`
	Barcode                     string    `json:"barcode"`
	Pin                         string    `json:"pin"`
	SpouseBirthdate             time.Time `json:"spouseBirthdate"`
	Birthday                    time.Time `json:"birthday"` // 出生日期
	VisaExpire                  time.Time `json:"visaExpire"`
	WorkPermitExpirationDate    time.Time `json:"workPermitExpirationDate"`
	DepartureDate               time.Time `json:"departureDate"`
	AdditionalNote              string    `json:"additionalNote"`
	Notes                       string    `json:"notes"`
	DepartureDescription        string    `json:"departureDescription"`
	Active                      bool      `json:"active"`
	WorkPermitScheduledActivity bool      `json:"workPermitScheduledActivity"`
	CreateDate                  time.Time `json:"createDate"`
	WriteDate                   time.Time `json:"writeDate"`
	LastAttendanceId            int       `json:"lastAttendanceId"`
	LastCheckIn                 time.Time `json:"lastCheckIn"`
	LastCheckOut                time.Time `json:"lastCheckOut"`
	ContractId                  int       `json:"contractId"`
	Vehicle                     string    `json:"vehicle"`
	FirstContractDate           time.Time `json:"firstContractDate"`
	ContractWarning             bool      `json:"contractWarning"`
	LeaveManagerId              int       `json:"leaveManagerId"`
	HourlyCost                  float64   `json:"hourlyCost"`
	PersonalMobile              string    `json:"personalMobile"`
	JoiningDate                 time.Time `json:"joiningDate"`
	IdExpiryDate                time.Time `json:"idExpiryDate"`
	PassportExpiryDate          time.Time `json:"passportExpiryDate"`
	ResignDate                  time.Time `json:"resignDate"`
	Resigned                    string    `json:"resigned"`
	Fired                       string    `json:"fired"`
	ExpenseManagerId            int       `json:"expenseManagerId"`
	ResourceCalendarIds         int       `json:"resourceCalendarIds"`
	Nation                      int       `json:"nation"`
	Schoolgrade                 int       `json:"schoolgrade"`
	Appellation                 int       `json:"appellation"`
	BookingNumAm                int       `json:"bookingNumAm"`
	BookingNumPm                int       `json:"bookingNumPm"`
	BookingNumNg                int       `json:"bookingNumNg"`
	PoliticsStatus              string    `json:"politicsStatus"`
	Tocompile                   string    `json:"tocompile"`
	AppellationCode             string    `json:"appellationCode"`
	Rank                        string    `json:"rank"`
	AppellationTime             time.Time `json:"appellationTime"`
	Note                        string    `json:"note"`
	Introduction                string    `json:"introduction"`
	GradeId                     int       `json:"gradeId"`
	RankId                      int       `json:"rankId"`
	NaturePosition              int       `json:"naturePosition"`
	SurgeryCert                 string    `json:"surgeryCert"`
	Inductiondate               time.Time `json:"inductiondate"`
	Performanceclass            string    `json:"performanceclass"`
	EduAppellation              string    `json:"eduAppellation"`
	EduCategory                 string    `json:"eduCategory"`
	PhysicianCert               int       `json:"physicianCert"`
	PharmacistCert              int       `json:"pharmacistCert"`
	NurseCert                   int       `json:"nurseCert"`
	OperateCert                 string    `json:"operateCert"`
	PrescriptionCert            string    `json:"prescriptionCert"`
	SpecialistId                int       `json:"specialistId"`
	NurseSpe                    string    `json:"nurseSpe"`
	SpecialistDate              time.Time `json:"specialistDate"`
	IsSpecialist                string    `json:"isSpecialist"`
	EduSchool                   string    `json:"eduSchool"`
	SurgeryGrade                int       `json:"surgeryGrade"`
	PracticeCateg               string    `json:"practiceCateg"`
	PhysicianAidCert            int       `json:"physicianAidCert"`
	NativePlaceP                int       `json:"nativePlaceP"`
	NativePlaceC                int       `json:"nativePlaceC"`
	GraduationDate              time.Time `json:"graduationDate"`
	IndentificationId           string    `json:"indentificationId"`
}

type BasicInfo struct {
	ID                 int64     `json:"id" bind:"required" msg:"用户名不能为空"`
	Name               string    `json:"name"`
	JobTitle           string    `json:"jobTitle"`
	MobilePhone        string    `json:"mobilePhone"`
	WorkEmail          string    `json:"workEmail"`
	WorkPhone          string    `json:"workPhone"`
	Nation             string    `json:"nation"`
	CountryId          int64     `json:"countryId"`
	Gender             int64     `json:"gender"`
	Birthday           time.Time `json:"birthday"`
	PlaceOfBirth       string    `json:"placeOfBirth"`
	CountryOfBirth     int64     `json:"countryOfBirth"`
	NativePlaceP       int64     `json:"nativePlaceP"`
	NativePlaceC       int64     `json:"nativePlaceC"`
	PoliticsStatus     string    `json:"politicsStatus"`
	AddressHomeId      string    `json:"addressHomeId"`
	PrivateEmail       string    `json:"privateEmail"`
	Phone              string    `json:"phone"`
	BankAccountId      string    `json:"bankAccountId"`
	KmHomeWork         int64     `json:"kmHomeWork"`
	IdentificationId   string    `json:"identificationId"`
	IdExpiryDate       time.Time `json:"idExpiryDate"`
	PassportId         int64     `json:"passportId"`
	IdAttachmentId     string    `json:"idAttachmentId"`
	Marital            int64     `json:"marital"`
	SpouseCompleteName string    `json:"spouseCompleteName"`
	SpouseBirthdate    time.Time `json:"spouseBirthdate"`
	Children           int       `json:"children"`
	EmergencyContact   string    `json:"emergencyContact"`
	EmergencyPhone     string    `json:"emergencyPhone"`
	Certificate        int       `json:"certificate"`
	SchoolGrade        int       `json:"schoolGrade"`
	GraduationDate     time.Time `json:"graduationDate"`
	StudyField         string    `json:"studyField"`
	StudySchool        string    `json:"studySchool"`
	VisaNo             string    `json:"visaNo"`
	PermitNo           string    `json:"permitNo"`
	VisaExpire         time.Time `json:"visaExpire"`
}
